name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: reviewdog/action-setup@v1

    - name: Set environment variables
      run: |
        echo "REPORTER=${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}" >> $GITHUB_ENV
        echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

    - name: clang-format
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: 'src'
        clangFormatVersion: 14
        inplace: True

    - name: Report clang-format
      run: |
        wget http://misc.nalajcie.org/reviewdog -O /tmp/reviewdog 2>/dev/null
        chmod +x /tmp/reviewdog
        /tmp/reviewdog -filter-mode=nofilter -f diff -name="clang-format" -f.diff.strip=1 -reporter=${{ env.REPORTER }}
        git stash -u && git stash drop ||:

    - name: flake8
      uses: reviewdog/action-flake8@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: ${{ env.REPORTER }}
        filter_mode: nofilter

    - name: black
      uses: reviewdog/action-black@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: ${{ env.REPORTER }}
        filter_mode: nofilter

